### ISSUE TITLE
Incorrect METAR decoded

### ISSUE THREAD

**Issue by Rolln-dev** [evogelsa/dcs-real-weather#52]
**Describe the bug**
Noticed that this METAR wasn't completely decoded correctly, specifically the cloud layers and winds should not be 0 at all layers.

**Attachments**
```log
2025/01/26 11:43:44 Got weather data: [{"metar_id":684529543,"icaoId":"PGUM","receiptTime":"2025-01-26 16:36:06","obsTime":1737908160,"reportTime":"2025-01-26 16:16:00","temp":26,"dewp":26,"wdir":50,"wspd":4,"wgst":null,"visib":"10+","altim":1008.5,"slp":null,"qcField":13,"wxString":null,"presTend":null,"maxT":null,"minT":null,"maxT24":null,"minT24":null,"precip":null,"pcp3hr":null,"pcp6hr":null,"pcp24hr":null,"snow":null,"vertVis":null,"metarType":"METAR","rawOb":"PGUM 261616Z COR 05004KT 10SM SCT015 SCT020 BKN029 26\/26 A2978 RMK AO2 $","mostRecent":1,"lat":13.4796,"lon":144.796,"elev":74,"prior":1,"name":"Guam\/Pat Intl, --, GU","clouds":[{"cover":"SCT","base":1500},{"cover":"SCT","base":2000},{"cover":"BKN","base":2900}]}]
2025/01/26 11:43:44 Parsing weather...
2025/01/26 11:43:44 Parsed weather
2025/01/26 11:43:44 Validating weather data...
2025/01/26 11:43:44 No ceiling data, defaulting to clear
2025/01/26 11:43:44 No elevation data, defaulting to 0 meters
2025/01/26 11:43:44 Weather data validated successfully
2025/01/26 11:43:44 Getting winds aloft data from Open Meteo...
2025/01/26 11:43:45 Got winds aloft data
2025/01/26 11:43:45 Parsing winds aloft data...
2025/01/26 11:43:45 Parsed winds aloft data: {0.81 7.36 149 275}
2025/01/26 11:43:45 Unpacking mission file...
2025/01/26 11:43:45 Source file: C:\Users\vnaon\Saved Games\DCS.LoneWarrior\Missions\VNAO_Naval_Det_Westpac_2.2.6.miz.orig
2025/01/26 11:43:45 Unpacked mission file
2025/01/26 11:43:45 Loading mission into Lua VM...
2025/01/26 11:43:46 Loaded mission into Lua VM
2025/01/26 11:43:46 Updating mission...
2025/01/26 11:43:46 Winds:
	At 8000 meters (26000 ft):
		Speed: 0.000 m/s (0 kt)
		From: 275
	At 2000 meters (6500 ft):
		Speed: 0.000 m/s (0 kt)
		From: 149
	At ground:
		Speed: 0.000 m/s (0 kt)
		From: 050
2025/01/26 11:43:46 Gusts: 0.000 m/s (0 kt)
2025/01/26 11:43:46 Temperature: 26.0 C (78.8 F)
2025/01/26 11:43:46 QNH: 1008 hPa (29.78 inHg)
2025/01/26 11:43:46 Fog:
	Thickness:  0 meters (0 feet)
	Visibility: 0 meters (0 feet)
	Enabled: false
2025/01/26 11:43:46 Dust:
	Visibility: 0 meters (0 feet)
	Enabled: false
2025/01/26 11:43:46 Clouds:
	Preset: "Preset19"
	Base: 0 meters (0 feet)
2025/01/26 11:43:46 Updated mission
2025/01/26 11:43:46 Writing new mission file...
2025/01/26 11:43:46 Wrote new mission file
2025/01/26 11:43:46 Repacking mission file...
2025/01/26 11:43:47 Repacked mission file
2025/01/26 11:43:47 Removed unpacked mission
2025/01/26 11:43:47 METAR: PGUM 261616Z 05000KT 10SM OVC000 BKN230 BKN310 26/26 A2978 NOSIG
```

**Expected behavior**
METAR should be more like this: `PGUM 261616Z 05004KT 10SM SCT015 SCT020 BKN029 26/26 A2978`

**Comment by evogelsa** [comment]
What version are you using, and can you please upload your config?

**Comment by Rolln-dev** [comment]
So this one is reporting some winds, but the cloud layers are incorrect.

2.0.0.2

```toml
#
# Real Weather Configuration
#

# This is the section for core configuration of Real Weather
[realweather]

# This section is where you define the paths to the input and output mission
# files for real weather to use. Paths can be relative (e.g. "mission.miz"), or
# they can be absolute (e.g. "C:/Users/myuser/dcs-missions/mission.miz"). If
# using a path with backslashes `\`, be sure to escape them with another
# backslash, e.g. C:\\Users\\myuser\\dcs-missions\\missions.miz.
[realweather.mission]
input = "C:\\Users\\dcs\\Saved Games\\DCS.GreatBallzOfFire\\Missions\\VNAO_Naval_Det_Westpac_2.2.6.miz.orig"      # path of mission to update
output = "realweather.miz" # path of updated mission to output

# These are options for updating the mission brief
[realweather.mission.brief]
add-metar = true # Adds a generated METAR to your brief

# insert-key specifies where to insert the RW METAR in the brief. Real Weather
# will replace whatever line follows the insert-key with the METAR. If you leave
# this empty with "", the METAR will instead be appended to the end of the brief
insert-key = "==Real Weather METAR=="

# Remarks are optional information to append to the end of the METAR. These
# have no functional impact but allow you to customize the METAR if desired.
# An example of how you may use this is provided, but you can disable with ""
remarks = "RMK Generated by DCS Real Weather"

# This is the section for determining how Real Weather logs information. Real
# weather will always output to stdout/console regardless of if logging is
# enabled. Setting enable to true will make Real Weather also output its log
# to the file specified.
[realweather.log]
enable = true
file = "realweather.log"


#
# API Configuration
#

# The API section determines how Real Weather will access its supported data
# providers.
[api]

# This determines the priority of METAR providers real weather will use. The
# first provider in the list is highest priority. The additional providers will
# be used as a fallback if the default provider does not respond or has an
# error. All available providers should be listed, even if not enabled
provider-priority = [
  "aviationweather",
  "checkwx",
  "custom",
]

# This is configuration for the aviationweather.gov METAR data provider. This
# provider is supplied by the US government and is free to use
[api.aviationweather]
enable = true

# This is configuration for the CheckWX METAR data provider. CheckWX is a
# private company supplying weather data from a variety of sources. The service
# requires creating a developer account for free at checkwxapi.com. Creating an
# account will provide you with an API key to use.
[api.checkwx]
enable = false
key = "" # required for CheckWX, see checkwxapi.com

# Enables getting custom weather data from a .json file specified by file.
# Weather in this file should be in the same format as provided by CheckWX. See
# checkwxapi.com or the examples in thie GitHub repo for reference.
[api.custom]
enable = false
file = "weather_data.json"

# override makes the data in the supplied file override anything retrieved from
# the APIs. If false, the custom data will only be used as a fallback if the
# APIs are not available.
override = true

# This is configuration for the OpenMeteo winds aloft data provider. This
# provider is only used for getting winds aloft data and will still require at
# least one of the above providers to be enabled. This API is free to use. If
# disabled, Real Weather will instead attempt to estimate winds aloft using
# ground wind information
[api.openmeteo]
enable = true


#
# Options configuration
#

# This is the section for configuring the various behaviors of real weather.
# These determine how Real Weather will work and operate.
[options]

# These settings determine how Real Weather will update the mission time
[options.time]
enable = false      # set to false to disable updating time
system-time = true # set to false if you want to use the METAR time
offset = "-4h"     # offset system or METAR time by this amount

# These settings determine how Real Weather updates mission weather
[options.weather]
enable = true # set to false to disable updating all weather

# the following two options are mutually exclusive, pick one to use. If both are
# configured, icao will be used
icao = "PGUM"  # Airport ICAO to retrieve METAR information from
icao-list = [] # List of ICAOs, randomly selects one to retrieve METAR from

runway-elevation = 50 # meters, used for adjusting cloud heights and wind calc

# Wind specific weather settings
[options.weather.wind]
enable = true     # set to false to disable wind updates
minimum = 0       # meters/second minimum wind value to set (must be >= 0)
maximum = 50      # meters/second maximum wind value to set (must be <= 50)
gust-minimum = 0  # m/s minimum gust to set (must be >=0)
gust-maximum = 50 # m/s maximum gust to set (must be <= 50)

# advanced options, used for calculating winds aloft if api.openmeteo.enable is
# set to false, otherwise these are unused.
stability = 0.143       # atmospheric stability, 0.143 is a sane default
fixed-reference = false # use a fixed referenced point for winds aloft

# Cloud specifc weather settings
[options.weather.clouds]
enable = true
fallback-to-legacy = true  # if no preset match is found, use legacy weather

[options.weather.clouds.base]
minimum = 0     # meters, lowest AGL altitude clouds will be set to (at least 0)
maximum = 15000 # meters, max AGL altitude for cloud base (at most 15000)

# Cloud preset specifc weather settings
[options.weather.clouds.presets]
# Default is the default preset to be used if no match found and
# fallback-to-legacy is false. This can also be "" to default to clear weather
default = "Preset10"

# The following is a list of presets that are disallowed. Real Weather will
# omit any of the presets included below when making its best-match selection.
# Uncomment the preset to add it to the disallowed list
disallowed = [
#  "Preset1",
#  "Preset2",
#  "Preset1",
#  "Preset2",
#  "Preset3",
#  "Preset4",
#  "Preset5",
#  "Preset6",
#  "Preset7",
#  "Preset8",
#  "Preset9",
#  "Preset10",
#  "Preset11",
#  "Preset12",
#  "Preset13",
#  "Preset14",
#  "Preset15",
#  "Preset16",
#  "Preset17",
#  "Preset18",
#  "Preset19",
#  "Preset20",
#  "Preset21",
#  "Preset22",
#  "Preset23",
#  "Preset24",
#  "Preset25",
#  "Preset26",
#  "Preset27",
#  "RainyPreset1",
#  "RainyPreset2",
#  "RainyPreset3",
#  "RainyPreset4",
#  "RainyPreset5",
#  "RainyPreset6",
#  "NEWRAINPRESET4",
]

# Fog specific weather settings
[options.weather.fog]
enable = true
thickness-minimum = 0     # meters, min fog thickness (must be >=0)
thickness-maximum = 1000  # meters, max fog thickness (must be <= 1000)
visibility-minimum = 0    # meters, min fog visibility (must be >= 0)
visibility-maximum = 6000 # meters, max fog visibility (must be <= 6000)

# Dust specific weather settings
[options.weather.dust]
enable = true
visibility-minimum = 300  # meters, min dust visibility (must be >= 300)
visibility-maximum = 3000 # meters, max dust visibility (must be <= 3000)

# Temperature specific weather settings
[options.weather.temperature]
enable = true

# Pressure specific weather settings
[options.weather.pressure]
enable = true
```

[realweather.log](https://github.com/user-attachments/files/18552360/realweather.log)
